### ISSUE TITLE
webiny/action-post-run uses node12 which will be deprecated soon

### ISSUE THREAD

**Issue by panekj** [jirutka/setup-alpine#3]
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: webiny/action-post-run, webiny/action-post-run, webiny/action-post-run, webiny/action-post-run

**Comment by mirabilos** [comment]
That would be https://github.com/webiny/action-post-run/issues/4

Do we need to do anything as users of this action if this dependency needs to be updated?

**Comment by mirabilos** [comment]
This still occurs, although I saw you forked webiny and fixed it there? No new release of setup-alpine contains it yet, though…
