### ISSUE TITLE
Add to docs how to use on host machine

### ISSUE THREAD

**Issue by jbbjarnason** [jirutka/setup-alpine#8]
Would it be possible to add to the readme how one could run this locally?

**Comment by jirutka** [comment]
What do you mean by locally? Using [act](https://github.com/nektos/act) or on a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)?

**Comment by jbbjarnason** [comment]
Using `act` or use the bash scripts to create chroot on hosts computer for debugging purposes.

**Comment by jirutka** [comment]
> Using `act`

I’ve never used it, so I dunno.

> use the bash scripts to create chroot on hosts computer for debugging purposes.

Well, you can just use [alpine-chroot-install](https://github.com/alpinelinux/alpine-chroot-install). It’s principally the same.
